apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-demo-deployment
spec:
  selector:
    matchLabels:
      app: spring-boot-demo-app
  replicas: 2
  template:
    metadata:
      labels:
        app: spring-boot-demo-app
    spec:
      containers:
      - name: spring-boot-demo-app
        image: 
        ports:
        - containerPort: 8080
          name: server
        - containerPort: 8081
          name: management